#ifndef UNTITLED_CONFIG_H
#define UNTITLED_CONFIG_H

#define MAX_SEND_SIZE 100
#define MAX_MESSAGES_BUFFER_SIZE 10

#define SENDER_MAXSIZE 128
#define DATA_MAXSIZE 2048

#define SERVER_IPV4_ADDR "127.0.0.1"
#define SERVER_LISTEN_PORT 3556


#define SERVER_QUEUE_NAME   "/testee"
#define CLIENT_QUEUE_NAME   "/testee2"
#define QUEUE_PERMISSIONS 0777
#define MAX_MESSAGES 10
#define MAX_MQ_MSG_SIZE 8192
#define MSG_BUFFER_SIZE MAX_MQ_MSG_SIZE + 10

#endif //UNTITLED_CONFIG_H
