#ifndef UNTITLED_CONFIG_H
#define UNTITLED_CONFIG_H

#define MAX_SEND_SIZE 100
#define MAX_MESSAGES_BUFFER_SIZE 10

#define SENDER_MAXSIZE 128
#define DATA_MAXSIZE 512

#define SERVER_IPV4_ADDR "127.0.0.1"
#define SERVER_LISTEN_PORT 3556

#endif //UNTITLED_CONFIG_H
